/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aoc;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.stream.Collectors;

public class App {
    private final List<Integer> input;

    public App(List<Integer> input) {
        this.input = input;
    }

    public Integer getSolutionPart1() {
        int result = 0;
        for (int i=0;i<input.size();i++) {
            if (isPrime(input.get(i))) {
                result += (i*input.get(i));
            }
        }
        return result;
    }

    public Integer getSolutionPart2() {
        int result = 0;
        for (int i=0;i<input.size();i++) {
            if (!isPrime(input.get(i))) {
                if (i%2 == 0) {
                    result += input.get(i);
                } else {
                    result -= input.get(i);
                }
            }
        }
        return result;
    }

    public static void main(String[] args) throws IOException {
        List<Integer> input = parseInput("input.txt");
        String part = System.getenv("part") == null ? "part1" : System.getenv("part");
        if (part.equals("part2"))
            System.out.println(new App(input).getSolutionPart2());
        else
            System.out.println(new App(input).getSolutionPart1());
    }

    private static List<Integer> parseInput(String filename) throws IOException {
        return Files.lines(Path.of(filename))
                .map(Integer::parseInt)
                .collect(Collectors.toList());
    }

    private boolean isPrime(int number) {
        if (number < 2) return false;
        if (number % 2 == 0) return (number == 2);
        int root = (int)Math.sqrt((double)number);
        for (int i = 3; i <= root; i += 2)
        {
            if (number % i == 0) return false;
        }
        return true;
    }
}
