/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aoc;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.util.Arrays;
import java.util.List;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

public class AppTest {
    private static final List<Integer> INPUT = List.of(199,200,208,210,200,207,240,269,260,263);
    App classUnderTest;

    @BeforeEach
    void createSubject() {
        classUnderTest = new App(INPUT);
    }

    @Test void part1SumsInput() {
        assertEquals(7, classUnderTest.getSolutionPart1());
    }

    @Test void part2MultipliesInput() {
        assertEquals(5, classUnderTest.getSolutionPart2());
    }

    @Test void test2() {
        var app = new App(null);
        //var list = Arrays.asList(3,4,3,1,2);
        var list = Arrays.asList(4,2,4,1,5,1,2,2,4,1,1,2,2,2,4,4,1,2,1,1,4,1,2,1,2,2,2,2,5,2,2,3,1,4,4,4,1,2,3,4,4,5,4,3,5,1,2,5,1,1,5,5,1,4,4,5,1,3,1,4,5,5,5,4,1,2,3,4,2,1,2,1,2,2,1,5,5,1,1,1,1,5,2,2,2,4,2,4,2,4,2,1,2,1,2,4,2,4,1,3,5,5,2,4,4,2,2,2,2,3,3,2,1,1,1,1,4,3,2,5,4,3,5,3,1,5,5,2,4,1,1,2,1,3,5,1,5,3,1,3,1,4,5,1,1,3,2,1,1,1,5,2,1,2,4,2,3,3,2,3,5,1,5,1,2,1,5,2,4,1,2,4,4,1,5,1,1,5,2,2,5,5,3,1,2,2,1,1,4,1,5,4,5,5,2,2,1,1,2,5,4,3,2,2,5,4,2,5,4,4,2,3,1,1,1,5,5,4,5,3,2,5,3,4,5,1,4,1,1,3,4,4,1,1,5,1,4,1,2,1,4,1,1,3,1,5,2,5,1,5,2,5,2,5,4,1,1,4,4,2,3,1,5,2,5,1,5,2,1,1,1,2,1,1,1,4,4,5,4,4,1,4,2,2,2,5,3,2,4,4,5,5,1,1,1,1,3,1,2,1);
        long count = 0;
        for(int i : list) {
            int[] p = new int[2];
            p[0] = i;
            p[1] = 256;
            count += app.countDays(p);
        }

        System.out.println(count);

        assertEquals(1,1);
    }
}
